### ISSUE TITLE
Uncaught Error: Could not load animation before running it

### ISSUE THREAD

**Issue by nachikamod** [dappsnation/ng-rive#22] opened 2021-07-19 04:00 UTC
Followed all the steps but, getting this log

`zone.js:182 Uncaught Error: Could not load animation before running it
    at RiveAnimationDirective.moveFrame (ng-rive.js:624)
    at MapSubscriber.project (ng-rive.js:618)
    at MapSubscriber._next (map.js:29)
    at MapSubscriber.next (Subscriber.js:49)
    at FilterSubscriber._next (filter.js:33)
    at FilterSubscriber.next (Subscriber.js:49)
    at SwitchMapSubscriber.notifyNext (switchMap.js:66)
    at SimpleInnerSubscriber._next (innerSubscribe.js:10)
    at SimpleInnerSubscriber.next (Subscriber.js:49)
    at MapSubscriber._next (map.js:35)
`

**Comment by localpcguy** [comment] 2021-07-26 17:39
We are seeing this same issue. Is it an implementation issue in our code or a bug that needs to be fixed? Or is it specific to the Rive animation being used? We haven't had a chance to dive into the source code to see what is throwing the error, but it seems to reproduce relatively easily.

**Comment by nachikamod** [comment] 2021-07-26 17:49
Don't know, I also haven't dug deeper into the library. But it's not implementation error and also not specific for any animation either for sure.

So I would suggest to tag these down as bug. I will notify you if I find any solution.

**Comment by localpcguy** [comment] 2021-07-28 19:48
It seems to have been related to the animation and either not specifying the artboard (on the canvas tag) or not specifying the name of the animation on the riv-animation element inside the canvas.

**Comment by nachikamod** [comment] 2021-07-30 06:53
As far as I understand from your comment it seems you are pointing to incorrect reference to animation. If that's the case then, nope I have properly specified name of the animation.

**Comment by GrandSchtroumpf** [comment] 2021-08-03 13:03
Hello, sorry for the delay, the error might come from [this line](https://github.com/dappsnation/ng-rive/blob/master/libs/ng-rive/src/lib/animation.ts#L152).
This can happen if the name or index of the animation you're providing in the `<riv-animation>` tag doesn't match any animation in your animation.
If you can provide a repo or a snippet of code I could maybe help here.
Let's take an example, if you want to use this animation: https://rive.app/preview/?filename=699-1369-simple-loader
Then the name of the name of the `<riv-animation>` should be "Animation 1" : 
```html
<!-- "loader" is the name of the file. By default it'll look here: asset/rive/loader.riv -->
<canvas width="500" height="500" riv="loader" fit="cover" alignment="center">
  <riv-animation name="Animation 1" play></riv-animation>
</canvas>
```
You need to specify the name of the animation because you can have multiple animations in the same canvas. For example this one has 9 animations: https://rive.app/preview/?filename=382-718-download-icon

You can take a look at the [playground application code](https://github.com/dappsnation/ng-rive/tree/master/apps/playground) if you want to see more examples.

Please let me know what part of the readme wasn't clear enough so I can improve it 🙂. I'm open for pull request too 😉

**Comment by localpcguy** [comment] 2021-08-09 21:28
Hopefully my comment above was clear, but it was a reference issue in our case. The name of the animation was not specified correctly. Thanks for the comment and thanks for the work in making this library! 

I don't really have specific recommendations for improving the README (or I'd submit a PR) but the thing I thought while reading through it was that it does assume a fair amount of knowledge about the RIVE animations and structure. I know this is a bit of a helper library, so it's purpose probably isn't to teach how to use RIVE animations, but where it makes sense to expound a little, that could be helpful. Obviously I understand that anything added could become out of date and that is a maintenance challenge with a library of this nature.

In addition, it doesn't always list all of the options, for example, for the Output events, we had to dive into the source code to figure out that they both existed and then figure out when and in what scenarios each one was used and fired. Actually, this one would probably be an area I could maybe update the README as it's fairly fresh and we kept some notes locally. Let me see what I can do.

**Comment by GrandSchtroumpf** [comment] 2021-08-11 10:21
Ok, thanks for the feedback. I'll close this issue as it seems to be fixed.
I created this issue to improve devX for debugging: https://github.com/dappsnation/ng-rive/issues/23
Concerning the readme I'll try to keep it more up-to-date with all inputs & outputs. Don't hesitate to open a specific issue or a PR on that matter.

**Closed by GrandSchtroumpf** 2021-08-11 10:21 UTC

**Comment by nachikamod** [comment] 2021-08-11 10:29
Thanks for the help guys. I saw the reference about name for animation in the README. But I wasn't clear about why it is used there, but again thanks for great support.
